apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s4r-server
  namespace: k8s4r-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s4r-server-role
rules:
- apiGroups:
  - robot.k8s4r.io
  resources:
  - robots
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - robot.k8s4r.io
  resources:
  - robots/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s4r-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s4r-server-role
subjects:
- kind: ServiceAccount
  name: k8s4r-server
  namespace: k8s4r-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s4r-server
  namespace: k8s4r-system
  labels:
    app: k8s4r-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s4r-server
  template:
    metadata:
      labels:
        app: k8s4r-server
    spec:
      serviceAccountName: k8s4r-server
      containers:
      - name: server
        image: k8s4r-server:latest
        imagePullPolicy: IfNotPresent
        command:
        - /server
        args:
        - --addr=:8080
        - --namespace=default
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s4r-server
  namespace: k8s4r-system
  labels:
    app: k8s4r-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s4r-server
